language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=1.6.10
  - DJANGO_VERSION=1.7.4
  - DJANGO_VERSION=1.8  
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION=1.7.4
    - python: "2.6"
      env: DJANGO_VERSION=1.8
  fast_finish: true

install:
  - pip install Django==$DJANGO_VERSION djangorestframework==3.0.5
  - pip install coveralls
script:
  coverage run --source=rest_framework_sav runtests.py
after_success:
  coveralls
